### PR TITLE
OpenTrail celery tasks

### PR DESCRIPTION
**Pull request by stugots**
This is the goldstone-server side of supporting OpenTrail celery tasks.

It will be merged into master, but I forked it off fabfile_cadf.  When fabfile_cadf is updated, I'll update this branch.

#### Testing instructions

These are written assuming that you already have your dev environment running in another code branch.

1. Go to http://hpcloud.com, login, and create a container to receive your audit logs.

    Make a note of the container name, and your project name.  ("10904988497247-Project")

2. $ cd django-opentrail
  $ git checkout celery_task
  $ git up
  $ python setup.py sdist

3. $ cd goldstone-server
  $ git checkout celery_task
  $ git up

  $ \# There've been schema changes, so we’ll start with a new db.
  $ dropdb goldstone -U postgres -h 127.0.0.1
  goldstone
  $ createdb goldstone -U postgres -h 127.0.0.1
  goldstone

  $ fab goldstone_init
  (fill in the usual responses)

4. $ \# Still in the goldstone-server directory, install the add-on.
  $ pip install --upgrade ../django-opentrail/dist/django-opentrail-0.0.tar.gz
  $ fab -f addon_fabfile.py install_addon:name=opentrail,settings=goldstone.settings.local_docker,install_dir=.
  $ fab -f installer_fabfile syncmigrate:settings=goldstone.settings.local_docker,install_dir=.

5. $ \# You must now restart your dev environment to pick up OpenTrail's celery tasks.
  $ cd goldstone-server
  $ bin/stop_dev_env.sh 

  $ # Wait for both VMs to power off!!!

  $ # After they have powered off...
  $ bin/start_dev_env.sh 

6. $ fab runserver
  (select local_docker.py)

7. $ \# In another terminal window:
  $ curl -X POST -d "username=admin&password=changeme" http://localhost:8000/accounts/login/

    (Replace "changeme" with the Django admin password you gave in the goldstone_init step.)

    (Copy (Cmd-C) the authorization token.)

8. In a browser:

   http://localhost:8000/docs/

   Copy (Cmd-V) the token from step 7 into the top row’s API key box.

   opentrail

   POST /opentrail/trails/

   Enter...

           Name: Anything.

           DestinationType: Swift

           DestinationParams:

              {"SwiftURL":"https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0",
                "SwiftUsername":"yourlogin",
                "SwiftPassword":"yourpassword",
                "SwiftTenantName":"10904988497247-Project",
                "SwiftContainerName":"yourcontainername",
                "SwiftKeyPrefix":"yourauditlogprefix"}

            Enter this as one string.  N.B.: No spaces around the ":"!

            Replace yourlogin with your hpcloud login.

            Replace yourpassword with your hpcloud password.

            Replace yourcontainername with the name of the container you created in step 1.

            Replace yourauditlogprefix with what each audit log filename should start with. (E.g., if you enter, "audit_log_", then the audit logs will be named audit_log_0, audit_log_1, audit_log_2, etc.)

            Set SwiftTenantName with the name of your project. It should be identical to mine, I think.

    "Try it out!"

    The response body should look like this:

    screen shot 2015-08-20 at 4 22 24 pm

9. The celery task will create a new audit log every ten minutes. Go back to your hpcloud dashboard, "browse" the container, and refresh the page.

     If you don't see anything, the first place to look is in /tmp/goldstone-server-celery.log on your laptop. Any exceptions in there?

10. You can download the audit logs to look at them.

     To see *most* of the persistent audit metadata, go to http://localhost:8000/admin/ and open the Log table. Each row has one audit log's persistent metadata.

    N.B. The Django admin doesn't display PickledObjectFields without a lot of work. To see *all* of the log metadata, do this:

        $ python
        > from opentrail.models import Log
        > from pprint import pprint
        > pprint(Log.objects.all())

### CODE REVIEW

**Comment by jxstanford** [comment]
1) bump fabric to 1.10.2 in django-opentrail?  already done in fabfile_cadf branch.
2) prompt coloring in other fabfiles is cyan for prompts, green for info, and red for errors.  make addon_fabfile the same?

**Comment by jxstanford** [comment]
Exception when celery kicks off the task:

```[2015-08-28 20:22:11,032: INFO/MainProcess] Task goldstone.core.tasks.update_persistent_graph[c3af16e7-ff8f-4095-8baa-ca58ede5497a] succeeded in 8.619157447s: None
[2015-08-28 20:23:35,008: INFO/Beat] Scheduler: Sending due task opentrail_dump (opentrail.tasks.dump)
[2015-08-28 20:23:35,011: INFO/MainProcess] Received task: opentrail.tasks.dump[246bfc60-35c2-4888-a7e6-f8e372efad57]
2015-08-28T20:23:35+0000 WARNING  elasticsearch   POST /events_2015-08-28//_count [status:400 request:0.039s]
[2015-08-28 20:23:35,272: WARNING/Worker-3] POST /events_2015-08-28//_count [status:400 request:0.039s]
[2015-08-28 20:23:35,273: ERROR/Worker-3] Trail row Trail code review test, UUID 61223807-4dc1-11e5-822d-b8e8563856e0. Skipping...
Traceback (most recent call last):
  File "/Users/stanford/.virtualenvs/goldstone-server/lib/python2.7/site-packages/opentrail/tasks.py", line 129, in dump
    auditdata = response.data["results"]    # pylint: disable=E1101
KeyError: 'results'
[2015-08-28 20:23:35,277: INFO/MainProcess] Task opentrail.tasks.dump[246bfc60-35c2-4888-a7e6-f8e372efad57] succeeded in 0.262875565s: None```

**Comment by jxstanford** [comment]
Time between celery task firing up should be parameterized and pulled into the settings file.

**Comment by stugots** [comment]
@jxstanford:

> 1) bump fabric to 1.10.2 in django-opentrail? already done in fabfile_cadf branch.

Fabric is at 1.10.1 in the fabfile_cadf branch.  Did you mean to bump it there?

**Comment by stugots** [comment]
@jxstanford:

> 2) prompt coloring in other fabfiles is cyan for prompts, green for info, and red for errors. make addon_fabfile the same?

I agree the colors used should be consistent.  I'll make the more consistent in addon_fabfile now.

When is no coloring used?

Are you suggesting that *all* prompts should be in cyan?  

This usage ought to be written down somewhere.

**Comment by stugots** [comment]
@jxstanford:

> Exception when celery kicks off the task:

Fixed in the django-opentrail project.

**Comment by stugots** [comment]
@jxstanford:

> Time between celery task firing up should be parameterized and pulled into the settings file.

If you mean parameterized through a fabric command, let's discuss.

**Comment by stugots** [comment]
I believe all comments prior to here have been addressed.

**Comment by jxstanford** [comment]
> Fabric is at 1.10.1 in the fabfile_cadf branch. Did you mean to bump it there?
I did.  If we know that fabric is a dependency of goldstone-server, do we need to express the dependency in the add-on?  

> When is no coloring used?
for all output other than messages, prompts and errors that we control.

> Are you suggesting that all prompts should be in cyan?
yes, if we create them.

> If you mean parameterized through a fabric command, let's discuss.
I meant that rather than hardcoding 10 minutes into the task code, we should refer to an app-specific django setting (not necessarily configurable via fabric) .  We can default it to 10 minutes in settings, but customer should be able to change and restart to have a new interval.

**Comment by stugots** [comment]
@jxstanford:

> Fabric is at 1.10.1 in the fabfile_cadf branch. Did you mean to bump it there?
> I did. If we know that fabric is a dependency of goldstone-server, do we need to express the dependency in the add-on?

Originally, I thought there was a good reason to codify fabric's version.  I thought there would be a fabfile in the django-opentrail project, but that's turned out to be unnecessary.

I'll remove the fabric dependency from setup.py.

> When is no coloring used?
> for all output other than messages, prompts and errors that we control.

So just printing something like, "Row successfully added," must be in a color?

I'd like to discuss this, because I've never seen that done in any software, and I don't understand what's driving this requirement.

> If you mean parameterized through a fabric command, let's discuss.
> I meant that rather than hardcoding 10 minutes into the task code, we should refer to an app-specific django setting (not necessarily configurable via fabric) . We can default it to 10 minutes in settings, but customer should be able to change and restart to have a new interval.

The customer can edit opentrail.settings.CELERYBEAT_SCHEDULE and then restart the web server.  Is this sufficient?

**Comment by jxstanford** [comment]
Can we settle on 'important' informational messages in green (or pick a color)?  I'd just like some visual consistency with other fab scripts.  Was shooting for differentiating our message from subsystem messages where it made sense.

**Comment by stugots** [comment]
@jxstanford:

> Can we settle on 'important' informational messages in green (or pick a color)? I'd just like some visual consistency with other fab scripts. Was shooting for differentiating our message from subsystem messages where it made sense.

I'm OK with that.

I think the existing branch code does this.  Important informational messages are in green, but normal ones are in white.   Try the current branch code and see if you agree.

**Comment by jxstanford** [comment]
good on the text coloring stuff.  :+1:   please merge into fabfile_cadf so that branch doesn't go to master without PR.  I'll work through the final PR details there and take it all to master.

**Comment by stugots** [comment]
OK.  I'll close this pull request and do it from the command line, because there's apparently no way to change the target branch from within github.

**Pull request closed without merging**
