### PR TITLE
Flatten compliance to submodule

### PR DESCRIPTION
**Pull request by jxstanford**
This PR replaces the previous addon management strategy with one based on git submodules, and an assumption that we know and control the universe of addons.  That assumption should be fairly easy to relax later, but seemed acceptable for the foreseeable future.

In addition, it incorporates #146 and extends it to provide REST API for SavedSearch operations.  There will be a parallel PR in the goldstone-compliance project that should be reviewed and tested at the same time.

Finally, there were some updates to logstash version (now 2.1) and rule handling to better support TRACEs, and API performance tracking.

To test:
* pull this branch and check it out
* `git submodule init`
* `git submodule update`
* `cd goldstone/compliance`
* `git checkout flatten_to_submodule`
* `cd ../..`
* `docker rm -f $(docker ps -qa)`
* `docker rmi goldstoneserver_gsappdev goldstoneserver_gsdbdvc goldstoneserver_gssearch goldstoneserver_gslog`
* run test suite
* start client and poke around (should see compliance addon installed now)
* test the /core/saved_search API and the /compliance/defined_search API
** should be 12 saved_searches
** should be 10 defined_searches

closes: #146
closes: #188
closes: #127

### CODE REVIEW

**Comment by lexjacobs** [comment]
* Started from fresh clone of branch from github.
* Ran `npm install` to get front-end dev dependencies.
* verified `grunt karma` passed.
* ran `bin/wipe_docker.sh` to start from clean slate in containers.
* ran `bin/start_dev_env.sh` to pull images and create containers and start server etc...
* logged in successfully
* mixed ability to make data api calls:
  * eventTimeline: no
  * nodeAvailability: yes
  * cloudTopology: yes
  * apiPerf / mem / cpu / disk: no
  * logBrowser: yes
  * event/api browser: no
* compliance addon ui does not appear, nor can compliance routes be manually navigated to. (no addon data in localStorage, so none was returned by the call to /addons)

terminal output attached.
Most errors look similar to
[Log at 2016-01-04 10.14.11.txt](https://github.com/Solinea/goldstone-server/files/77532/Log.at.2016-01-04.10.14.11.txt)
:
```
gsappdev_1 | 2016-01-04T18:24:04+0000 ERROR    goldstone.core.utils type object 'EventData' has no attribute 'field_has_raw'
gsappdev_1 | Traceback (most recent call last):
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
gsappdev_1 |     response = handler(request, *args, **kwargs)
gsappdev_1 |   File "/home/app/goldstone/drfes/views.py", line 50, in get
gsappdev_1 |     queryset = self.filter_queryset(self.get_queryset())
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/rest_framework/generics.py", line 149, in filter_queryset
gsappdev_1 |     queryset = backend().filter_queryset(self.request, queryset, self)
gsappdev_1 |   File "/home/app/goldstone/drfes/filters.py", line 120, in filter_queryset
gsappdev_1 |     operation)
gsappdev_1 |   File "/home/app/goldstone/drfes/filters.py", line 41, in _add_query
gsappdev_1 |     if view.Meta.model.field_has_raw(param):
gsappdev_1 | AttributeError: type object 'EventData' has no attribute 'field_has_raw'
gsappdev_1 | [04/Jan/2016 18:24:04] "GET /core/events/search/?timestamp__range={%22gte%22:1451930944619,%22lte%22:1451931844619}&page_size=100 HTTP/1.1" 500 160
```

**Comment by jxstanford** [comment]
@lexjacobs can you confirm that you also changed into the goldstone/compliance folder and checked out the appropriate branch?

**Comment by lexjacobs** [comment]
@jxstanford 

sorry - i edited to the comment after posting it because I had forgotten to mention that I had init/updated/checked out the proper submodule branch.

**Comment by jxstanford** [comment]
ok, let me start from scratch locally and see if I can recreate the issue.

**Comment by lexjacobs** [comment]
Successfully navigating app and all charts load as expected. Call to `addons` still returning []

**Comment by jxstanford** [comment]
@lexjacobs the addon is created as a Django fixture the first time you create the app and DB containers.  It's possible that your env build got messed up along the way.  Could you `docker rm -f $(docker ps -aq)` and try again?  My output after wiping all images and containers is:

**Comment by lexjacobs** [comment]
Call to `/addons/` still returning `[]`

After `docker rm -f $(docker ps -aq)` and restarting the containers, site loads properly.

Background processes showing that compliance tasks are running:

```
gsappdev_1 | [2016-01-04 22:36:00,046: INFO/Beat] Scheduler: Sending due task vulnerability_check (goldstone.compliance.tasks.vulnerability_check)
gsappdev_1 | [2016-01-04 22:36:00,049: INFO/MainProcess] Received task: goldstone.compliance.tasks.vulnerability_check[a752e843-019f-4686-8a16-54ecf1597c9a]
gsappdev_1 | [2016-01-04 22:36:00,052: INFO/Beat] Scheduler: Sending due task nova-hypervisors-stats (goldstone.nova.tasks.nova_hypervisors_stats)
gsappdev_1 | [2016-01-04 22:36:00,053: INFO/Worker-2] Starting new HTTPS connection (1): security.openstack.org
gsappdev_1 | [2016-01-04 22:36:00,056: INFO/MainProcess] Received task: goldstone.nova.tasks.nova_hypervisors_stats[8e3c8b67-1a26-4c58-8656-aeea8f1c2e93]
gsappdev_1 | [2016-01-04 22:36:00,057: INFO/Beat] Scheduler: Sending due task log_event_search (goldstone.core.tasks.log_event_search)
gsappdev_1 | [2016-01-04 22:36:00,058: INFO/MainProcess] Received task: goldstone.core.tasks.log_event_search[c2cd2157-4b65-474c-a3ed-cfea7ad2d7f0]
gsappdev_1 | [2016-01-04 22:36:01,780: INFO/MainProcess] Task goldstone.compliance.tasks.vulnerability_check[a752e843-019f-4686-8a16-54ecf1597c9a] succeeded in 1.729437236s: None
```

image

**Comment by jxstanford** [comment]
Try:

```docker rm -f $(docker ps -qa)
docker rmi goldstoneserver_gsappdev_1 goldstoneserver_gsdbdvc
```

Then restart.  Please capture all startup log messages for review.

**Comment by lexjacobs** [comment]
Startup log messages attached:

[Log at 2016-01-04 14.58.45.txt](https://github.com/Solinea/goldstone-server/files/77814/Log.at.2016-01-04.14.58.45.txt)

Addon not added.

Confirming that I can manually add the compliance via http://localhost:8000/admin/addons/addon/ , and the client UI works as expected at that point.
But it's not loading at startup, even after performing the `docker rm / rmi` actions above.

**Comment by jxstanford** [comment]
@lexjacobs just pushed a fix for the fixture loading problem.  it was picking up a fixtures file in the npm_modules folder and bombing out.  I've retrofitted to only look in the goldstone subdir.  Please try again.

**Comment by lexjacobs** [comment]
Confirming used `git up` to sync to latest version of `goldstone/server:flatten_compliance_to_submodule` .

No addon registered after restarting containers.
Ran `docker rm -f $(docker ps -aq)`
Still no addon registered.

Will now try 
`docker rm -f $(docker ps -qa)` WITH `docker rmi goldstoneserver_gsappdev_1 goldstoneserver_gsdbdvc`
and report if addon is loaded during startup.

Current terminal output included fyi:
[Log at 2016-01-04 15.38.40.txt](https://github.com/Solinea/goldstone-server/files/77851/Log.at.2016-01-04.15.38.40.txt)

**Comment by jxstanford** [comment]
sorry, it updates the docker_entrypoint, so you will need to rmi the app and dbdvc images.

**Comment by lexjacobs** [comment]
Of note: 

* Compliance addon loaded properly and UI element exists.
* I was able to create a lease.
* I was not able to create an OpenTrail trail. Error was that `container doesn't exist` , but container was confirmed in existence as I could still log into it at `https://horizon.hpcloud.com/project/containers/alex_demo/` . Error may be unrelated to addon code, as hpcloud is shutting down soon.
* Other UI elements showing up properly.
* 10 `/compliance/defined_search`es
* 12 `/core/saved_search`es

:+1: 

After this PR is merged, I will rebase my outstanding client work on top of this and submit my own PR.

**Comment by bhuvan-rk** [comment]
Can we add a section in HACKING.md for submodules ?

This includes submodule init, cleanup, update, reset etc + how to commit to submodules + how to test submodule changes

**Comment by lexjacobs** [comment]
Perhaps of note:

Restarting app containers produced the following error during startup:

```
gsdb_1     | ERROR:  duplicate key value violates unique constraint "addons_addon_name_key"
gsdb_1     | DETAIL:  Key (name)=(compliance) already exists.
gsdb_1     | STATEMENT:  INSERT INTO "addons_addon" ("name", "version", "manufacturer", "url_root", "notes", "updated") VALUES ('compliance', '0.1', 'Solinea, Inc.', 'compliance', '', NULL) RETURNING "addons_addon"."id"
gsappdev_1 | Traceback (most recent call last):
gsappdev_1 |   File "manage.py", line 23, in <module>
gsappdev_1 |     execute_from_command_line(sys.argv)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
gsappdev_1 |     utility.execute()
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
gsappdev_1 |     self.fetch_command(subcommand).run_from_argv(self.argv)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
gsappdev_1 |     self.execute(*args, **cmd_options)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
gsappdev_1 |     output = self.handle(*args, **options)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
gsappdev_1 |     self.loaddata(fixture_labels)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 90, in loaddata
gsappdev_1 |     self.load_label(fixture_label)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 147, in load_label
gsappdev_1 |     obj.save(using=self.using)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 173, in save
gsappdev_1 |     models.Model.save_base(self.object, using=using, raw=True)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
gsappdev_1 |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
gsappdev_1 |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
gsappdev_1 |     using=using, raw=raw)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
gsappdev_1 |     return getattr(self.get_queryset(), name)(*args, **kwargs)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
gsappdev_1 |     return query.get_compiler(using=using).execute_sql(return_id)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
gsappdev_1 |     cursor.execute(sql, params)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
gsappdev_1 |     return super(CursorDebugWrapper, self).execute(sql, params)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
gsappdev_1 |     return self.cursor.execute(sql, params)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
gsappdev_1 |     six.reraise(dj_exc_type, dj_exc_value, traceback)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
gsappdev_1 |     return self.cursor.execute(sql, params)
gsappdev_1 | django.db.utils.IntegrityError: Problem installing fixture '/home/app/goldstone/compliance/fixtures/compliance_initial_data.yaml': Could not load addons.Addon(pk=None): duplicate key value violates unique constraint "addons_addon_name_key"
gsappdev_1 | DETAIL:  Key (name)=(compliance) already exists.
gsappdev_1 |
gsappdev_1 | Requirement already satisfied (use --upgrade to upgrade): tox==2.1.1 in /venv/lib/python2.7/site-packages (from -r test-requirements.txt (line 1))
``

**Comment by lexjacobs** [comment]
Also confirming lease successfully terminated at scheduled time.

**Comment by jxstanford** [comment]
@bhuvan-rk issue #203 
@lexjacobs issue #202

**Comment by lexjacobs** [comment]
fyi
image

**Comment by bhuvan-rk** [comment]
@lexjacobs : this error is harmless. It simply indicates that loaddata is attempting to load the same fixture twice. I'm working on a fix for it. will raise an issue. 


gsdb_1     | ERROR:  duplicate key value violates unique constraint "addons_addon_name_key"
gsdb_1     | DETAIL:  Key (name)=(compliance) already exists.
gsdb_1     | STATEMENT:  INSERT INTO "addons_addon" ("name", "version", "manufacturer", "url_root", "notes", "updated") VALUES ('compliance', '0.1', 'Solinea, Inc.', 'compliance', '', NULL) RETURNING "addons_addon"."id"
gsappdev_1 | Traceback (most recent call last):

:
:
:
gsappdev_1 | django.db.utils.IntegrityError: Problem installing fixture '/home/app/goldstone/compliance/fixtures/compliance_initial_data.yaml': Could not load addons.Addon(pk=None): duplicate key value violates unique constraint "addons_addon_name_key"
gsappdev_1 | DETAIL:  Key (name)=(compliance) already exists.

**Comment by bhuvan-rk** [comment]
@jxstanford :  In class SavedSearchFilter(ElasticFilter) add_query() function does not add a new query but returns an execute-ready query statement. 

Can we change its name to build_query() ? 

Is this so named because front-end will call this view to add a new query to the list of saved searches ?

**Comment by jxstanford** [comment]
@bhuvan-rk I think the whole REST/ES interface is subject to review based on the new SavedSearch functionality.  Can we kick the renaming down the road a bit?

**Comment by bhuvan-rk** [comment]
:+1:

**Pull request merged**
