### PR TITLE
update compose files for production and test

### PR DESCRIPTION
**Pull request by jxstanford**
* Brings the compose files up to version 2 specifications and adds the canary container for GSE versions.  
* Bumps version of docker-compose to 1.6.2
* Updates the INSTALL doc accordingly.
* Makes the goldstone-prod.env file a %config file in RPM's eyes so it is preserved with a .rpmsave suffix when the package is removed.
* Unsets default values for passwords in the environment file to force users to set their own

I tested installs against Kilo for both enterprise and oss packages, and all seems to check out.  Welcome to have others try, or you can just take a look at https://10.10.22.60:8443 (username: gsadmin, password: xyz123).

closes: #473 

@slashk @lexjacobs @vichargrave

### CODE REVIEW

**Comment by jxstanford** [comment]
@lexjacobs could you look at the circleci run and see if you can figure out why the client tests failed?

**Comment by lexjacobs** [comment]
@jxstanford re: failed client tests, those are the same intermittent spurious errors that show up locally. I have committed some test changes on the topology extraction branch that should hopefully improve the situation. There seems to be some race conditions involving the sheer volume of ajax requests that are jammed through the test runner. No definitive answer for the source yet but tuning in progress. Rerunning the tests generally results in 0 errors. The errors reported are not reflective of the code, but only the test mechanism.

**Comment by lexjacobs** [comment]
the tests on this branch failed the first time and then when I reran them they succeeded. scratching head.

image

**Comment by lexjacobs** [comment]
development environment checks out. I do not have current vpn credentials to check out the link you pasted.

**Comment by vichargrave** [comment]
Everything seems to be working at https://10.10.22.60:8443.  Just FYI in case you don't know, this version does not have the issue-470 changes.  Otherwise it looks OK to me.

**Comment by lexjacobs** [comment]
Thanks for the credential files. I was able to successfully login. Open source features look fine. I'm not sure if this has been running for at least 4 hours, but no vulnerabilities have been downloaded 2 the Vulnerability Advisor tab.

If that is to be expected, then 👍

**Comment by lexjacobs** [comment]
Confirming that this system looks to have been running for more than 4 hours. So if you are also expecting the compliance functionality to be working, that would be my only reason for not giving the thumbs-up.

**Comment by lexjacobs** [comment]
image

storage and cpu not registering any amount used.

**Comment by jxstanford** [comment]
@lexjacobs the vulnerabilities missing highlights the need for a GSE task container.  I'll add that and ping you when I think it's working.  When I extracted celery from the app container, it only gets the OSS code, so can't run GSE tasks :-(

I'll also spawn a VM or two so we can see resource usage.  

@vichargrave I would not expect to see #470 in there at this point.

**Comment by jxstanford** [comment]
fixed the migrations and task issues that were identified.  verified on 10.10.22.60.  Merging based on pre-auth from @lexjacobs

**Pull request merged**
