### PR TITLE
Django-admin, who is not non-tenant-admin, can request and change tenant data, but can't get to the "tenant settings" page

### PR DESCRIPTION
**Pull request by stugots**
GET /user/ will now return:

    {"last_login": "2015-07-20T05:41:41.768569Z",
      "username": "admin",
      "first_name": "",
      "last_name": "",
      "email": "root@localhost",
      "date_joined": "2015-07-20T05:41:41.768569Z",
      "tenant_admin": false,
      "is_superuser": true,
      "default_tenant_admin": false,
      "uuid": "6f73b75d-3eb9-4e80-a297-53cdf743eded"
    }

The change is the addition of the, "*is_superuser*," key.  Its value will be either *true* or *false*.

If true, the user is a Django admin. A.k.a., a Goldstone admin. If false, the user is a standard user account.

The name comes from the Django attribute of the same name. It's different than our other attributes, but it'd be nice to keep it identical to Django's attribute, and avoid an alias.

Pylint:
* master: 9.73 / 10 / 10 / 10
* this pull: 9.75 / 10 / 10 / 10

### CODE REVIEW

**Comment by lexjacobs** [comment]
The `last_login` key on the GET /user/ dict doesn't seem to reflect the date of the previous login. I logged out with /accounts/logout/ , followed by a login with /accounts/login/ .
The `last_login` key didn't change.

Also noticing the return value in the pasted screen shot above to be  

```
{
    "last_login":  "2015-07-20T05:41:41.768569Z",....
```

**Comment by lexjacobs** [comment]
Confirming client changes reflect new is_superuser key, and it returns true for a Goldstone Admin, and false for a tenant admin.

**Comment by stugots** [comment]
This is a djoser bug. As it turns out, the latest release includes a fix for it.

You'll have to upgrade djoser *and* reset your database.

So:

    $ # In your "fab runserver" window...
    $ git up
    $ pip install -r requirements.txt
    
    $ # In your workon window...
    $ ^C
    $ # Wait for the VMs to power off
    $ bin/start_dev_env.sh

    $ # Back in your "fab runserver" window...
    $ fab runserver
    $ (local_docker.py)

    $ # In a third window...
    $ workon goldstone-server
    $ dropdb goldstone -U postgres -h 127.0.0.1
    goldstone
    $ createdb goldstone -U postgres -h 127.0.0.1
    goldstone
    $ fab goldstone_init
    (blah blah woof woof)

You should now see the "last_login" attribute reflect the account's last login.

**Comment by lexjacobs** [comment]
:+1:

**Pull request merged**
