### PR TITLE
Resolve ids found in events

### PR DESCRIPTION
**Pull request by stugots**
This fulfills the, "resolve ids found in events event," ticket.

This has new celery task code, a new Python package, and db schema changes. After this is merged, you will need to:

1. deactivate
2. pip install -r requirements.txt
3. workon goldstone-server
4. fab goldstone_init

(There are shortcuts around some of this, but it's simpler to do the update this way.)

Pylint:
* master today: 9.51 / 10 / 9.70
* this request: 9.54 / 10 / 9.70

### CODE REVIEW

**Comment by lexjacobs** [comment]
:+1:

**Comment by jxstanford** [comment]
I don't think your instructions are accurate.  The `pip install` command would be installing requirements outside of the virtualenv, and would most likely fail unless you had an env var set to allow it.

**Comment by stugots** [comment]
You are correct.  That was a summary.  I am happy to write up explicit line-by-line instructions, if they're needed.

**Comment by jxstanford** [comment]
After restarting celery and refreshing goldstone via goldstone_init, I still get 'unknown' for all fields in all events.  Image:  https://goo.gl/photos/cWZZNtYMymFkA82w6

The update_graph task does not report any errors:

[2015-07-01 18:35:56,782: INFO/MainProcess] Task goldstone.core.tasks.update_graph[baeb9172-6a6e-407e-bfa2-93295954f9d4] succeeded in 56.745971189s: None

**Comment by stugots** [comment]
> After restarting celery and refreshing goldstone via goldstone_init, I still get 'unknown' for all fields in all events. Image: https://goo.gl/photos/cWZZNtYMymFkA82w6
>
> The update_graph task does not report any errors:

Let's see what's in your resource graph. Please paste the output of this:

```
$ python
>>> from goldstone.core import resource
>>> from goldstone.core.models import PolyResource
>>> from pprint import print
>>> pprint(resource.instances.graph.nodes())
>>> pprint([x.resourcetype for x in resource.instances.graph.nodes()])
>>> pprint([x.attributes.get("name") for x in resource.instances.graph.nodes()])
>>> pprint([x.cloud_attributes for x in PolyResource.objects.all()])
>>> exit()
```

**Comment by jxstanford** [comment]
Here's the output:  https://gist.github.com/jxstanford/b9eb64ca3c468cf86caa

**Comment by stugots** [comment]
I was right the first time, the in-memory graph needs lazy evaluation because the processes run in different memory spaces.

I pushed up a fix. Try it.

**Comment by jxstanford** [comment]
:+1:

**Pull request merged**
