### PR TITLE
Fixes several issues with logstash filtering

### PR DESCRIPTION
**Pull request by jxstanford**
- identifies swift messages properly
- dedups some cinder messages that were going to local and daemon facilities
- fixes the backend handling of spawn failure events, and adds handling for instance quota violations

- also changes the canary image tag to "stable" instead of "latest" for GSE compose files

To test, you will need to drop your containers and images goldstone images, then start the development environment.

### CODE REVIEW

**Comment by jxstanford** [comment]
@vichargrave circleci is failing on a strange error.  I suspect an image was corrupted during push.  Trying to push them again, but hotel internet sucks.  I'd wait to review until at least the backend tests in circle are passing.

**Comment by jxstanford** [comment]
@vichargrave I think it's all clear.  The build problem is fixed...

**Comment by vichargrave** [comment]
gs-docker-ent.bintray.io/goldstone-svc-canary lable is still "latest".

**Comment by jxstanford** [comment]
@vichargrave in which compose file?

**Comment by vichargrave** [comment]
Looks good on the swift component log entries, but I'm not getting a swift component in the service status  panel because the core_monitoredservice table does not contain such an entry.

**Comment by jxstanford** [comment]
The service would be dynamically discovered if there were API calls that fit the typical format for other openstack calls.  You can try to use the swift API to generate some traffic, but I would consider this out of scope for the current PR.

**Comment by vichargrave** [comment]
👍

**Pull request merged**
