### PR TITLE
Saved search dropdown api/event/logs

### PR DESCRIPTION
**Pull request by lexjacobs**
### also has minor css change in goldstone-compliance under separate PR.

To test, pull branch and navigate to

- #reports/logbrowser
- #reports/apibrowser
- #reports/eventbrowser

and check that the predefined searches in the dropdowns are as expected.

Then...
click on the gear next to any of the predefined search dropdowns and create a new predefined search for api/log/event.
Navigate back to the reports and verify that your predefined searches show up in the dropdown list.
Also, please test updating and deletion of your own predefined searches.

**your custom predefined searches in events/api will not trigger chart changes. That functionality is ticketed and will be handled then.**

image

image

### CODE REVIEW

**Comment by jxstanford** [comment]
Some general changes to headers and buttons:

image

**Comment by jxstanford** [comment]
Applies to all viewers.

image

**Comment by jxstanford** [comment]
Applies to all:

image

**Comment by jxstanford** [comment]
Don't quite understand the statement about wiring up the search.  When you create it, you should have a refreshed list in the "predefined search" dropdown.  When it's selected, the call should be made to /saved_search/{uuid} just like any other search.  

If you're concerned about whether the search is well formed and has the right aggregation to draw the chart, don't be.  Consider this MVP.  We'll work on validation both on the front/back.  For now, assume that the search will:
a) be well formed with proper aggregation
b) be bell formed without aggregation (maybe then put a popup alert in the chart: "No chart data defined in search"
c) be poorly formed and you will get an error response back from server, then show a popup alert and go back to the default search.

To test each scenario:

a) take query from any of existing searches that works, and save it as a new one.
b) same as above, but remove the `aggs` block
c) use `{}` as the query

**Comment by lexjacobs** [comment]
### updates headings and button tags:

screen shot 2016-02-04 at 10 08 37 am
screen shot 2016-02-04 at 10 08 33 am
screen shot 2016-02-04 at 10 08 27 am

### updates dropdown title with current saved search
#### works with i18n as it takes the text from the dom for the title. so if the title was entered in another language, or translated, the dropdown title will be as well.
screen shot 2016-02-04 at 12 50 30 pm
screen shot 2016-02-04 at 12 50 45 pm
screen shot 2016-02-04 at 12 50 50 pm



### pretty prints (only works with valid JSON):
#### and sets input to a text area, not just a single line input field.

screen shot 2016-02-04 at 12 46 25 pm

**Comment by jxstanford** [comment]
:+1:

**Pull request merged**
