### PR TITLE
updates to start_dev_env

### PR DESCRIPTION
**Pull request by jxstanford**
This PR addresses some of the startup script madness that we've had to deal with recently.  Specifically:

- puts celery into a docker container (development only for now, see #473)
- updates docker-compose files to version 2
- removes support for running celery locally
- provides additional flags for bin/start_dev_env.sh:
    --app-location=local | container
    --app-edition=oss | gse
- also provides support for a "none" value for --stack-vm and --docker-vm flags

@joraldaz @lexjacobs @vichargrave please test.

@joraldaz : `bin/start_dev_env.sh --app-location=local --docker-vm=none`
@vic : `bin/start_dev_env.sh --app-location=local --app-edition=gse`
@lexjacobs : `bin/start_dev_env.sh --app-edition=gse`

### CODE REVIEW

**Comment by lexjacobs** [comment]
` $ bin/start_dev_env.sh --app-edition=gse`
fails with the following terminal output:

```  
17:24 $ bin/start_dev_env.sh --app-edition=gse

Running with the following settings:
    APP_EDITION = gse
    APP_LOCATION = container
    COMPOSE_FILE = compose-containerapp-gse.yml
    DOCKER_VM = default
    STACK_VM = RDO-kilo

Waiting for VM "RDO-kilo" to power on...
VM "RDO-kilo" has been successfully started.
(default) Starting VM...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
ERROR: In file './compose-containerapp-gse.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
(goldstone-server) ~/devel/goldstone-server [local_dev|…untracked: 1]
17:26 $ bin/start_dev_env.sh --app-edition=gse

Running with the following settings:
    APP_EDITION = gse
    APP_LOCATION = container
    COMPOSE_FILE = compose-containerapp-gse.yml
    DOCKER_VM = default
    STACK_VM = RDO-kilo

"RDO-kilo" {eb126011-7419-41fc-a0b0-612e49a7c1a2}
RDO-kilo is already running
"default" {1198f39f-a14e-436c-9282-74edb32816ee}
default is already running
ERROR: In file './compose-containerapp-gse.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
(goldstone-server) ~/devel/goldstone-server [local_dev|…untracked: 1]
17:31 $


```

**Comment by jxstanford** [comment]
@lexjacobs you need to be running docker-compose >= 1.6.  Maybe time to update docker toolbox.

**Comment by lexjacobs** [comment]
`stop_dev_env.sh` produces the following error:


```
17:53 $ ./bin/stop_dev_env.sh --stop-docker --stop-stack
"default" {1198f39f-a14e-436c-9282-74edb32816ee}
ERROR: .IOError: [Errno 2] No such file or directory: u'./docker-compose-dev.yml'
shutting down docker VM
(default) Stopping VM...
"RDO-kilo" {eb126011-7419-41fc-a0b0-612e49a7c1a2}
Waiting for RDO-kilo to poweroff...
```

**Comment by jxstanford** [comment]
@lexjacobs use ctrl-C in the window that you ran `start_dev_env.sh` instead.  I've pushed removal of `stop_dev_env.sh`.

**Comment by lexjacobs** [comment]
updated docker-compose to version 1.7.0
current error listed below:
```
18:04 $ !511
docker-compose -v
docker-compose version 1.7.0, build 0d7bf73
(goldstone-server) ~/devel/goldstone-server [local_dev|…untracked: 1]
18:06 $ bin/start_dev_env.sh --app-edition=gse

Running with the following settings:
    APP_EDITION = gse
    APP_LOCATION = container
    COMPOSE_FILE = compose-containerapp-gse.yml
    DOCKER_VM = default
    STACK_VM = RDO-kilo

"RDO-kilo" {eb126011-7419-41fc-a0b0-612e49a7c1a2}
RDO-kilo is already running
"default" {1198f39f-a14e-436c-9282-74edb32816ee}
default is already running
Building gstask
Step 1 : FROM solinea/goldstone-base:1.1.0-SNAPSHOT.96.g7ae8d2e.develop
 ---> 49ed9a4c1a83
Step 2 : MAINTAINER Luke Heidecke <luke@solinea.com>
 ---> Using cache
 ---> e36106ac1439
Step 3 : ENV DJANGO_ADMIN_EMAIL "root@localhost" DJANGO_ADMIN_PASSWORD "goldstone" GOLDSTONE_PASSWORD "goldstone" GOLDSTONE_TENANT_ADMIN_PASSWORD "goldstone" POSTGRES_PASSWORD "goldstone"
 ---> Using cache
 ---> 1d991bf48a67
Step 4 : ENV DJANGO_SETTINGS_MODULE goldstone.settings.docker DJANGO_ADMIN_USER admin GOLDSTONE_REDIS_HOST gstaskq CELERY_LOGLEVEL info
 ---> Using cache
 ---> e3c5c3ce4cb2
Step 5 : COPY goldstone-server/ ${APPDIR}/
ERROR: Service 'gstask' failed to build: lstat goldstone-server/: no such file or directory
(goldstone-server) ~/devel/goldstone-server [local_dev ↓·1|…untracked: 1]
18:07 $

```

**Comment by jxstanford** [comment]
@lexjacobs pushed what I hope is a fix for that.

**Comment by lexjacobs** [comment]
gstask container successfully builds, but database connection status == DOWN

necessary to wipe and re-create all images?


```
18:34 $ !483
bin/start_dev_env.sh --app-edition=gse

Running with the following settings:
    APP_EDITION = gse
    APP_LOCATION = container
    COMPOSE_FILE = compose-containerapp-gse.yml
    DOCKER_VM = default
    STACK_VM = RDO-kilo

"RDO-kilo" {eb126011-7419-41fc-a0b0-612e49a7c1a2}
RDO-kilo is already running
"default" {1198f39f-a14e-436c-9282-74edb32816ee}
default is already running
Building gstask
Step 1 : FROM solinea/goldstone-base:1.1.0-SNAPSHOT.96.g7ae8d2e.develop
 ---> 49ed9a4c1a83
Step 2 : MAINTAINER Luke Heidecke <luke@solinea.com>
 ---> Using cache
 ---> e36106ac1439
Step 3 : ENV DJANGO_ADMIN_EMAIL "root@localhost" DJANGO_ADMIN_PASSWORD "goldstone" GOLDSTONE_PASSWORD "goldstone" GOLDSTONE_TENANT_ADMIN_PASSWORD "goldstone" POSTGRES_PASSWORD "goldstone"
 ---> Using cache
 ---> 1d991bf48a67
Step 4 : ENV DJANGO_SETTINGS_MODULE goldstone.settings.docker DJANGO_ADMIN_USER admin GOLDSTONE_REDIS_HOST gstaskq CELERY_LOGLEVEL info
 ---> Using cache
 ---> e3c5c3ce4cb2
Step 5 : COPY goldstone-server/ ${APPDIR}/
 ---> 740cd0263b85
Removing intermediate container 14354c2648df
Step 6 : COPY docker-entrypoint.sh /
 ---> 11b09bfd1838
Removing intermediate container b770dd2750fa
Successfully built 11b09bfd1838
WARNING: Image for service gstask was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building gsapp
Step 1 : FROM solinea/goldstone-base:1.0.1-SNAPSHOT.33.gf857d73.local_dev
1.0.1-SNAPSHOT.33.gf857d73.local_dev: Pulling from solinea/goldstone-base
f8efbffe7b95: Already exists
a3ed95caeb02: Already exists
05862d742dc3: Already exists
38f8c9754a53: Already exists
83a4f731401f: Already exists
d7e72118be39: Already exists
c3227fc9f315: Already exists
9172a3792bdf: Pull complete
d5dc52b79048: Pull complete
4ffd5533b942: Pull complete
8f7e6ff11038: Pull complete
Digest: sha256:f0bfab96af1214b0355773681ec8274e0d0f5616e77a0a6c51ad8def36a00488
Status: Downloaded newer image for solinea/goldstone-base:1.0.1-SNAPSHOT.33.gf857d73.local_dev
 ---> afafcc0526ec
Step 2 : MAINTAINER Luke Heidecke <luke@solinea.com>
 ---> Running in 1c1fada961f1
 ---> d98b862dee1b
Removing intermediate container 1c1fada961f1
Step 3 : ENV DJANGO_ADMIN_EMAIL "root@localhost" DJANGO_ADMIN_PASSWORD "goldstone" GOLDSTONE_PASSWORD "goldstone" GOLDSTONE_TENANT_ADMIN_PASSWORD "goldstone" POSTGRES_PASSWORD "goldstone"
 ---> Running in 7177855ca669
 ---> 5be02640bbb9
Removing intermediate container 7177855ca669
Step 4 : ENV DJANGO_SETTINGS_MODULE goldstone.settings.docker DJANGO_ADMIN_USER admin GOLDSTONE_REDIS_HOST gstaskq CELERY_LOGLEVEL info
 ---> Running in 717feb38d9f5
 ---> f372bb4aef0d
Removing intermediate container 717feb38d9f5
Step 5 : COPY goldstone-server/ ${APPDIR}/
 ---> ad30cc49727f
Removing intermediate container 322fb48aea19
Successfully built ad30cc49727f
WARNING: Image for service gsapp was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Recreating goldstoneserver_gsdb_1
Recreating goldstoneserver_gssearch_1
Recreating goldstoneserver_gstaskq_1
Recreating goldstoneserver_gskibana_1
Recreating goldstoneserver_gslog_1
Creating goldstoneserver_gsapp_1
Creating goldstoneserver_gstask_1
Attaching to goldstoneserver_gstaskq_1, goldstoneserver_gsdb_1, goldstoneserver_gssearch_1, goldstoneserver_gskibana_1, goldstoneserver_gslog_1, goldstoneserver_gsapp_1, goldstoneserver_gstask_1
gstaskq_1   |                 _._
gstaskq_1   |            _.-``__ ''-._
gstaskq_1   |       _.-``    `.  `_.  ''-._           Redis 3.0.4 (00000000/0) 64 bit
gstaskq_1   |   .-`` .-```.  ```\/    _.,_ ''-._
gstaskq_1   |  (    '      ,       .-`  | `,    )     Running in standalone mode
gstaskq_1   |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
gstaskq_1   |  |    `-._   `._    /     _.-'    |     PID: 1
gstaskq_1   |   `-._    `-._  `-./  _.-'    _.-'
gstaskq_1   |  |`-._`-._    `-.__.-'    _.-'_.-'|
gstaskq_1   |  |    `-._`-._        _.-'_.-'    |           http://redis.io
gstaskq_1   |   `-._    `-._`-.__.-'_.-'    _.-'
gstaskq_1   |  |`-._`-._    `-.__.-'    _.-'_.-'|
gstaskq_1   |  |    `-._`-._        _.-'_.-'    |
gstaskq_1   |   `-._    `-._`-.__.-'_.-'    _.-'
gstaskq_1   |       `-._    `-.__.-'    _.-'
gstaskq_1   |           `-._        _.-'
gstaskq_1   |               `-.__.-'
gstaskq_1   |
gstaskq_1   | 1:M 14 Apr 01:36:04.051 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
gstaskq_1   | 1:M 14 Apr 01:36:04.055 # Server started, Redis version 3.0.4
gstaskq_1   | 1:M 14 Apr 01:36:04.055 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
gstaskq_1   | 1:M 14 Apr 01:36:04.056 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
gstaskq_1   | 1:M 14 Apr 01:36:04.056 * The server is now ready to accept connections on port 6379
gsdb_1      | waiting for server to start....FATAL:  data directory "/var/lib/postgresql/data" has group or world access
gsdb_1      | DETAIL:  Permissions should be u=rwx (0700).
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gssearch_1  | [2016-04-14 01:36:06,559][INFO ][node                     ] [0be7fcffd5fb] version[1.7.1], pid[1], build[b88f43f/2015-07-29T09:54:16Z]
gssearch_1  | [2016-04-14 01:36:06,575][INFO ][node                     ] [0be7fcffd5fb] initializing ...
gssearch_1  | [2016-04-14 01:36:06,959][INFO ][plugins                  ] [0be7fcffd5fb] loaded [], sites [HQ, head]
gssearch_1  | [2016-04-14 01:36:07,192][INFO ][env                      ] [0be7fcffd5fb] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [163.9gb], net total_space [195.8gb], types [ext4]
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":50,"err":"Request error, retrying -- connect ECONNREFUSED","msg":"","time":"2016-04-14T01:36:07.272Z","v":0}
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":40,"msg":"Unable to revive connection: http://gssearch:9200/","time":"2016-04-14T01:36:07.283Z","v":0}
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":40,"msg":"No living connections","time":"2016-04-14T01:36:07.288Z","v":0}
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":30,"msg":"Unable to connect to elasticsearch at http://gssearch:9200. Retrying in 2.5 seconds.","time":"2016-04-14T01:36:07.291Z","v":0}
gsdb_1      | .... stopped waiting
gsdb_1      | pg_ctl: could not start server
gsdb_1      | Examine the log output.
goldstoneserver_gsdb_1 exited with code 1
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":40,"msg":"Unable to revive connection: http://gssearch:9200/","time":"2016-04-14T01:36:09.796Z","v":0}
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":40,"msg":"No living connections","time":"2016-04-14T01:36:09.796Z","v":0}
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":30,"msg":"Unable to connect to elasticsearch at http://gssearch:9200. Retrying in 2.5 seconds.","time":"2016-04-14T01:36:09.796Z","v":0}
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":40,"msg":"Unable to revive connection: http://gssearch:9200/","time":"2016-04-14T01:36:12.300Z","v":0}
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":40,"msg":"No living connections","time":"2016-04-14T01:36:12.300Z","v":0}
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":30,"msg":"Unable to connect to elasticsearch at http://gssearch:9200. Retrying in 2.5 seconds.","time":"2016-04-14T01:36:12.301Z","v":0}
gssearch_1  | [2016-04-14 01:36:12,822][INFO ][node                     ] [0be7fcffd5fb] initialized
gssearch_1  | [2016-04-14 01:36:12,865][INFO ][node                     ] [0be7fcffd5fb] starting ...
gssearch_1  | [2016-04-14 01:36:13,009][INFO ][transport                ] [0be7fcffd5fb] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/172.18.0.4:9300]}
gssearch_1  | [2016-04-14 01:36:13,044][INFO ][discovery                ] [0be7fcffd5fb] goldstone/ih6S3hgwSmKMqftywkPdtg
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":40,"msg":"Unable to revive connection: http://gssearch:9200/","time":"2016-04-14T01:36:14.806Z","v":0}
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":40,"msg":"No living connections","time":"2016-04-14T01:36:14.807Z","v":0}
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":30,"msg":"Unable to connect to elasticsearch at http://gssearch:9200. Retrying in 2.5 seconds.","time":"2016-04-14T01:36:14.807Z","v":0}
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gssearch_1  | [2016-04-14 01:36:16,819][INFO ][cluster.service          ] [0be7fcffd5fb] new_master [0be7fcffd5fb][ih6S3hgwSmKMqftywkPdtg][0be7fcffd5fb][inet[/172.18.0.4:9300]], reason: zen-disco-join (elected_as_master)
gssearch_1  | [2016-04-14 01:36:17,024][INFO ][http                     ] [0be7fcffd5fb] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/172.18.0.4:9200]}
gssearch_1  | [2016-04-14 01:36:17,024][INFO ][node                     ] [0be7fcffd5fb] started
gssearch_1  | [2016-04-14 01:36:17,578][INFO ][gateway                  ] [0be7fcffd5fb] recovered [16] indices into cluster_state
gssearch_1  | [2016-04-14 01:36:18,552][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-14] Type [audit.http.response] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:18,565][INFO ][cluster.metadata         ] [0be7fcffd5fb] [events_2016-04-14] creating index, cause [auto(bulk api)], templates [ceilo_events_template.json], shards [1]/[0], mappings [_default_, audit.http.response]
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gssearch_1  | [2016-04-14 01:36:21,035][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [compute.instance.shutdown.start] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:21,038][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [compute.instance.delete.start] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:21,058][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [compute.instance.update] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:21,062][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [port.delete.end] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:21,076][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [audit.http.response] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:21,085][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [compute.instance.exists] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:21,093][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [compute.instance.delete.end] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:21,125][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [compute.instance.shutdown.end] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:21,130][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [identity.authenticate] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:21,161][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [audit.http.request] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:21,181][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-13] Type [port.delete.start] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,072][DEBUG][action.admin.cluster.health] [0be7fcffd5fb] observer: timeout notification from cluster service. timeout setting [5s], time since start [7.6s]
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":30,"msg":"No existing kibana index found","time":"2016-04-14T01:36:25.107Z","v":0}
gskibana_1  | {"name":"Kibana","hostname":"2578abe029f2","pid":1,"level":30,"msg":"Listening on 0.0.0.0:5601","time":"2016-04-14T01:36:25.151Z","v":0}
gssearch_1  | [2016-04-14 01:36:25,239][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-14] Type [audit.http.response] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,267][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [compute.instance.create.end] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,280][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [compute.instance.power_off.end] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,297][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [compute.instance.power_off.start] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,300][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [compute.instance.create.start] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,356][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [scheduler.select_destinations.start] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,360][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [port.create.start] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,379][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [compute.instance.update] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,381][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [audit.http.response] contains a '.', it is recommended not to include it within a type name
gsapp_1     | Database connection status: DOWN
gssearch_1  | [2016-04-14 01:36:25,401][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [compute.instance.exists] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,447][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [compute.instance.power_on.start] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,535][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [port.create.end] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,553][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [scheduler.select_destinations.end] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,555][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [identity.authenticate] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,566][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [compute.instance.power_on.end] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:25,583][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-12] Type [audit.http.request] contains a '.', it is recommended not to include it within a type name
gstask_1    | Database connection status: DOWN
gssearch_1  | [2016-04-14 01:36:26,476][TRACE][index.indexing.slowlog.index] [0be7fcffd5fb] [events_2016-04-14][0] took[573.5ms], took_millis[573], type[audit.http.response], id[aff76e67-d24e-4864-a04e-717956d91992], routing[], source[{"raw":{},"timestamp":"2016-04-14T01:36:15.258197","traits":{"typeURI":"http://schemas.dmtf.org/cloud/audit/1.0/event","eventTime":"2016-04-14T01:36:15.211430+0000","initiator_host_address":"172.24.4.100","initiator_typeURI":"service/security/account/user","service":"nova-api","target_name":"nova","eventType":"activity","reason_code":"200","target_id":"openstack:4bbd20bbe32b40a8953fc924e43a4d41","observer_id":"target","initiator_id":"openstack:6248c2002b1a48bdbbb80550cda9ad99","target_typeURI":"service/compute/flavors/flavor","initiator_name":"ceilometer","request_id":"req-77b77fc4-446d-471f-a49b-12bb4cfe982a","action":"read","outcome":"success","id":"openstack:f2deb3c1-61ec-4f55-9909-e03ae3debd1c","requestPath":"/v2/8531b0d6032f4aac9d44378f7fd0569d/flavors/1"}}]
gssearch_1  | [2016-04-14 01:36:26,501][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-14] Type [audit.http.response] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:26,515][INFO ][cluster.metadata         ] [0be7fcffd5fb] [events_2016-04-14] update_mapping [audit.http.response] (dynamic)
gssearch_1  | [2016-04-14 01:36:26,534][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-14] Type [audit.http.request] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:26,627][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-14] Type [audit.http.request] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:36:26,628][INFO ][cluster.metadata         ] [0be7fcffd5fb] [events_2016-04-14] update_mapping [audit.http.request] (dynamic)
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gssearch_1  | [2016-04-14 01:36:37,282][INFO ][cluster.metadata         ] [0be7fcffd5fb] [logstash-2016.04.14] update_mapping [syslog] (dynamic)
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gssearch_1  | [2016-04-14 01:36:43,420][INFO ][cluster.metadata         ] [0be7fcffd5fb] [logstash-2016.04.14] update_mapping [syslog] (dynamic)
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gssearch_1  | [2016-04-14 01:37:03,063][INFO ][cluster.metadata         ] [0be7fcffd5fb] [api_stats-2016.04.14] creating index, cause [auto(bulk api)], templates [api_stats_template.json], shards [1]/[0], mappings [_default_, api_stats]
gssearch_1  | [2016-04-14 01:37:03,152][INFO ][cluster.metadata         ] [0be7fcffd5fb] [api_stats-2016.04.14] update_mapping [api_stats] (dynamic)
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gssearch_1  | [2016-04-14 01:37:16,730][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-14] Type [identity.authenticate] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:37:16,773][WARN ][index.mapper             ] [0be7fcffd5fb] [events_2016-04-14] Type [identity.authenticate] contains a '.', it is recommended not to include it within a type name
gssearch_1  | [2016-04-14 01:37:16,778][INFO ][cluster.metadata         ] [0be7fcffd5fb] [events_2016-04-14] update_mapping [identity.authenticate] (dynamic)
gssearch_1  | [2016-04-14 01:37:17,558][INFO ][cluster.metadata         ] [0be7fcffd5fb] [logstash-2016.04.14] update_mapping [syslog] (dynamic)
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | Database connection status: DOWN
gstask_1    | Database connection status: DOWN
gsapp_1     | PostgreSQL not available.  Exiting.
goldstoneserver_gsapp_1 exited with code 1
gstask_1    | PostgreSQL not available.  Exiting.
goldstoneserver_gstask_1 exited with code 1
```

**Comment by jxstanford** [comment]
yes, probably do need to wipe everything out.  there were changes to goldstone-base, so you need to make sure that image is gone too.

**Comment by lexjacobs** [comment]
👍

**Comment by lexjacobs** [comment]
What is the best way to shutdown virtual box without the stop script?

**Comment by vichargrave** [comment]
Canary and local seem to be working.  👍

**Pull request merged**
