### PR TITLE
Issue 446

### LINKED ISSUE #446: develop logstash patterns for RFC5424 formatted messages
From Kilo to Liberty, the default logging behavior has changed (for the better).  It now uses RFC5424 formatted log lines, so instead of something like this (Kilo):

```<182>2016-04-05T01:18:33.296106+00:00 rdo-kilo journal: 2016-04-05 01:18:33.243 1210 INFO keystone.openstack.common.service [-] Started child 2648```

We get something like this:

```<30>2016-04-05T00:37:39.577550+00:00 rsrc-03.c1.lab.solinea.com ceilometer-polling: 2016-04-05 00:37:39.576 22271 INFO ceilometer.agent.manager [-] Polling pollster disk.device.write.bytes in the context of meter_source```

We should have logstash patterns that recognize both formats.  Currently, since we don't recognize the new format, we don't categorize the openstack messages based on the component.  The patterns file is in `docker/goldstone-log/patterns`.  

There is already some logic to analyze the syslog-specific header, so our pattern should really only need to worry about this part of the example message:

```ceilometer-polling: 2016-04-05 00:37:39.576 22271 INFO ceilometer.agent.manager [-] Polling pollster disk.device.write.bytes in the context of meter_source``` 

So, a new pattern for OPENSTACK_RFC5424_MESSAGE would break it down into the following fields:

```
component = ceilometer
subcomponent = polling
timestamp = 2016-04-05 00:37:39.576
pid = 22271
loglevel = INFO
program = ceilometer.agent.manager
request_id_list = -
openstack_message = Polling pollster disk.device.write.bytes in the context of meter_source
```

Once the pattern is developed, the logstash filter that determines the component should be updated to only set the component if it's not already set.  The file that does this processing is `docker/goldstone-log/conf.d/34-filter-opestack-syslog`

### PR DESCRIPTION
**Pull request by rsmitty**
Closes #446. This new pattern will catch the RFC5424 logs in Liberty, including the audit logs. However, with catching the new audit logs, there are "new" components that will need to be mapped to their correct OpenStack friendly names. For example:

screen shot 2016-04-06 at 5 07 01 pm

`object` should actually map to `swift` in the component section. There is also one for `containers` that I spotted, which I presume will map to `magnum`. I suppose a new issue should be created for that piece?

### CODE REVIEW

**Comment by rsmitty** [comment]
@steve-wormley @jxstanford

**Comment by jxstanford** [comment]
@rsmitty re: object and container, yes.  We'll have to do some updates to logstash rule processing to handle that as well as jump around the block that does the component identification based on syslog facility.  Another ticket coming.

**Comment by rsmitty** [comment]
Don't merge yet! I forgot Steve's rules file he updated.

**Comment by jxstanford** [comment]
standing by

**Comment by rsmitty** [comment]
Okay, now ready to roll. Added in the 33* filter for rfc5424.

**Pull request merged**
