### PR TITLE
first crack at fixing intermittent docker vm startup (issue-187)

### PR DESCRIPTION
**Pull request by jxstanford**

### CODE REVIEW

**Comment by lexjacobs** [comment]
Not fixed locally.

I stopped containers and rdo.
Quit iTerm.
Re-opened iTerm.
`cd ~/devel/goldstone-server`
`eval $(docker-machine env default)` (just to test that "default" was not running). error thrown, confirming it was not yet running.

`bin/start_dev_env.sh`

exited with failure message:
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`

Full output attached:

[issue-187.txt](https://files.zenhub.io/567af41087e69855518ec7ba)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by lexjacobs** [comment]
with `set -x`

[with_set_-x.txt](https://files.zenhub.io/567af8aa87e69855518ec7e5)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by lexjacobs** [comment]
ran `docker-machine upgrade default` and tried again from a state where containers and vm were stopped.

Same error resulted.

[afterUpgrade.txt](https://files.zenhub.io/567afb8f87e69855518ec80d)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by lexjacobs** [comment]
after re-creating `default` docker vm.

sat in limbo for 4 minutes before erroring.

**Comment by lexjacobs** [comment]
Performed a fresh install of the operating system this weekend (not a backup from time machine, but starting from scratch).

error message remains:
```
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
```


prompted by this message, I regenerated certs with 'docker-machine regenerate-certs default' ...

```
Waiting for VM "RDO-kilo" to power on...
VM "RDO-kilo" has been successfully started.
(default) Starting VM...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: getsockopt: connection refused
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

...followed by a shutdown of containers and vms, closed iTerm, reopened and tried `bin/start_dev_env.sh` again. Same error.


Full terminal output attached.

[post-reinstall.txt](https://github.com/Solinea/goldstone-server/files/73425/post-reinstall.txt)

currently trying to remedy pycadf import error. rebuilding containers. pending...

**Comment by jxstanford** [comment]
the issue seems to be upstream interaction between docker and virtualbox.  abandoning this work since it is not a fix.

**Pull request closed without merging**
