### PR TITLE
Core api calls endpoints

### PR DESCRIPTION
**Pull request by lexjacobs**
Working on top of the branch that @stugots opened to create api endpoints for /core/apiperf/(search|summarize) ...

This pull request:

* reorganizes the top menu bar links to be more sensibly restful
* adds a drop down menu item for 'Api Browser' and related route and backbone page view
* creates apiHistorgramCollection to process api call before sending it to the view
* creates base class for sortable dataTable that uses "servserside: true"
* implements _all_regexp as a elasticSearch search method in this view, and retrofits to logAnalysis
* prepares view for next step of dynamic switching between bar chart and stacked bars
* updates tests

image

### CODE REVIEW

**Comment by stugots** [comment]
:+1:

**Comment by jxstanford** [comment]
would like to see `grunt lintAndTest` passing.

**Comment by lexjacobs** [comment]
@jxstanford `grunt lintAndTest` healed.

current remaining errors in log stream:

`[15/Jul/2015 05:49:13] "GET /nova/hypervisor/spawns/?@timestamp__range=%7B%22gte%22:1436935753549,%22lte%22:1436939353549%7D&interval=2.5m HTTP/1.1" 500 254`
**error expected** as /spawns/ route does not seem to load in current containerized environment.


`[15/Jul/2015 05:55:38] "GET /api_perf/stats/?@timestamp__range=%7B%22gte%22:1436936138324,%22lte%22:1436939738324%7D&interval=60s&component=keystone HTTP/1.1" 401 58`
**error expected** as call is made as part of test suite to prove 401 will cause redirect to /#login page after logging out.

**Comment by lexjacobs** [comment]
@jxstanford  @stugots 
I incorrectly mentioned needing a local username/password combo of
"admin / solinea"
The actual combo needed (as is currently coded into the e2e tests for auth purposes) is:
"gsadmin / solinea"
as that will cause certain screens to appear for the e2e test suite that would otherwise not due to a difference in user permissions in "admin" and "gsadmin".

**Comment by jxstanford** [comment]
:+1:

**Pull request merged**
