### PR TITLE
Widening service status view to accommodate possible FQDNs in that panel

### LINKED ISSUE #479: Service Status text is funky
Still looking at the GStone snapshot version (Version : 1.0.1-SNAPSHOT.0.g8922853.start_version_1.0.1) we were talking about yesterday, it appears that the Service Status pane is showing some crazy behavior on Firefox and some less weird behavior on Chrome. Seems as if the pane is having trouble dealing with some pretty long host names from the lab. The Chrome one at least wraps the text down below, but looks kind of odd when it extends under the "Service" column.

Firefox:
screen shot 2016-04-14 at 2 56 39 pm

Chrome:
screen shot 2016-04-14 at 2 56 48 pm

### PR DESCRIPTION
**Pull request by lexjacobs**
before:
image

after:
image

closes #479

### CODE REVIEW

**Comment by jxstanford** [comment]
Do you also need to adjust the table col widths?  When I messed around with it in my browser, I needed to do something like 50, 25, the 25 to ensure something like "controller-1.c2.lab.solinea.com" fit without wrapping in a full width window on my laptop.

**Comment by lexjacobs** [comment]
Sorry, I was following the issue ticket too literally and didn't check with an actual fqdn. I will play around with the different widths.

**Comment by lexjacobs** [comment]
old: 
screen shot 2016-05-10 at 1 29 03 pm

new:
screen shot 2016-05-10 at 1 29 26 pm


pushing latest changes now.

**Comment by jxstanford** [comment]
👍

**Pull request merged**
