### PR TITLE
POST /opentrail/trails/ version 1

### PR DESCRIPTION
**Pull request by stugots**
This fulfills the goldstone-server portion of the, "POST opentrail/trails/" ticket.

Pylint:
* master today: 9.66 / 10 / 9.82 / 10
* this pull: 9.67 / 10 / 9.82 / 10

Changes beyond, "getting it to work":
* Removed Python 2.6 reference from HACKING.
* Add Python 2.7.10 requirement to INSTALL and HACKING.
* Added PolyResource table to Django's admin.
* Removed duplicate reference to django.contrib.contenttypes from INSTALLED_APPS.
* Moved the utc_now() definition into the only module still using it.
* Added "v" as an allowed variable in pylint, because "for k,v in foo.iteritems()" is a common Python idiom.

To interactively test this:

1. Git up/pull in the post_trails branches of the goldstone-server and django-opentrail projects.
2. In django-opentrail, do a "python setup.py sdist".
4. Do these:

           $ dropdb goldstone_docker -U postgres -h 127.0.0.1 
           $ createdb goldstone_docker -U postgres -h 127.0.0.1

           $ fab goldstone_init

           $ pip install --upgrade ../django-opentrail/dist/django-opentrail-0.0.tar.gz

           $ fab -f addon_fabfile.py install_addon:name=opentrail,install_dir=.,settings=goldstone.settings.local_docker 
           $ fab -f installer_fabfile syncmigrate:settings=goldstone.settings.local_docker,install_dir=.

           $ fab runserver 
           (select local_docker…)

Then, surf to localhost:8000/docs/ in your browser.

1. Paste your login api key (from a curl command) into the api key box at the top of the page. 
2. opentrail 
3. POST /opentrail/trails/

    Use these arguments:

    name = whatever you want. But it must already exist within the HP Helion container.
    type = Swift
    DestinationParams = Here's what I used:

        {"SwiftURL":"https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0", 
        "SwiftUsername":"jderosa", 
        "SwiftPassword":"your login password", 
        "SwiftTenantName":"your project name", 
        "SwiftContainerName”:”your container name, which must exist", 
        "SwiftKeyPrefix”:”currently unused"}

4. "Try it out!"

You should receive a response like this:
				       
screen shot 2015-08-14 at 2 03 11 pm

### CODE REVIEW

**Comment by lexjacobs** [comment]
In instructions above, for using swagger,
params should be:
**Name** = whatever you want. But it must already exist within the HP Helion container.
**DestinationType** = Swift

**Comment by jxstanford** [comment]
I know we talked about the 2.7.10 thing, but I forgot what the issue was with versions < 2.7.10.  Could you remind me?  The docker container we are working on has 2.7.9, so just want to head off any issues we may have there.

**Comment by jxstanford** [comment]
:+1:

**Comment by lexjacobs** [comment]
:+1:

**Comment by stugots** [comment]
@jxstanford:

When using Python < 2.7.10, the authentication call to python-swiftclient gets an SSL error.  Alex experienced this. I don't have a screenshot of it because we worked on it in real-time while in Tucson. But since he had to upgrade his dev environment, his memory may be fresher than mine.

**Pull request merged**
