### PR TITLE
Saved search client

### PR DESCRIPTION
**Pull request by lexjacobs**
also includes https://github.com/Solinea/goldstone-compliance/pull/41

to test:
* check out branch
* navigate to http://localhost:8000/#reports/logbrowser and click the gear to get to the settings page
* create/update/delete searches to test
* navigate back to http://localhost:8000/#reports/logbrowser to see if your searches were added to the drop down.

sets up ui and editing page/forms for saved searches.

quick fixes:
placeholder in resource list on topology page.
axis adjustments for resources usage charts on discover page.

### CODE REVIEW

**Comment by jxstanford** [comment]
Backend:  Django admin should display useful fields (uuid, name, description, protected, index_prefix) in summary list.

**Comment by jxstanford** [comment]
Frontend: Form should required timestamp field value, and allow description field.

**Comment by lexjacobs** [comment]
sort on "description" not returning different results:

displayed below: 
two queries that differ by the "ordering" field. '-description' vs 'description'
yet the record with the different description shows up in the last index position.


`http://localhost:8000/core/saved_search/?page_size=25&page=1&ordering=-description&index_prefix=logstash-*`

image


`http://localhost:8000/core/saved_search/?page_size=25&page=1&ordering=description&index_prefix=logstash-*`

image

**Comment by lexjacobs** [comment]
Committed fix for adding 'description' to the submit and update forms.
Prepopulates 'description' with "Defined Search" to match field of all "core" and "compliance" owned searches.

image

image

**Comment by lexjacobs** [comment]
Confirming sort for SavedSearch.description is working.
Removed default value for description.
Kept 'required' in forms for description as server requires a value.

**Comment by jxstanford** [comment]
:+1:

**Pull request merged**
