### PR TITLE
New dashboard

### PR DESCRIPTION
**Pull request by lexjacobs**
This pull request:

* implements the new dashboard theme
* adjusts the necessary urls.py, views.py, and templates.
* imports a number of new graphical assets for the site navigation
* sets up click listeners of new site nav
* collapses extra backbone view base classes into single classes
* improves integration with many views into the base classes (to be continued on future ticket)
* adjusts css rules
* adds additional nav buttons on page views triggered by main nav buttons
* updates tests

Tickets will be created for:

* issues brought up during the PR process that may be outside of the scope of the PR.
* continuing the process of improving the integration of views into the base classes.

### CODE REVIEW

**Comment by jxstanford** [comment]
when a browser alert is present, the right veritical menu should push down as well.

image

**Comment by jxstanford** [comment]
White on gray!!!!

image

**Comment by jxstanford** [comment]
I think you mentioned this already, but username/email?


image

**Comment by jxstanford** [comment]
Change term to "Storage"


image

**Comment by jxstanford** [comment]
To avoid confusion, let's remove the user settings from this page, and only have them available through the top-right control.  If you want to put a copy of the lookback and interval settings in here as a placeholder, ok, or just hide the icon until we have something to put there.

image

**Comment by jxstanford** [comment]
This wierd purple block thing is weird.  Can we do different shades for selection or some other visual cue? 

image

**Comment by jxstanford** [comment]
multiple clicks on alert icon doesn't work.  it opens/closes once, then you have to click another icon before it is active again.

**Comment by jxstanford** [comment]
Seems like we should shrink the right margin a bit (say by 50%) to get a more comfortable feel.

**Comment by lexjacobs** [comment]
Fixed popover text color / changed 'disk' to 'storage' on discover view / hid 'chart settings' from sidebar nav for now.

Ticketing remaining issues and merging/closing ticket.

**Pull request merged**
