### PR TITLE
Adds goldstone-desktop as a submodule

### PR DESCRIPTION
**Pull request by lexjacobs**
@slashk assigning to John, but feel free to review.

goldstone-server/desktop branch deleted. will be replaced with submodule.

Sets up goldstone-desktop as a submodule. Initial commits in goldstone-desktop set from my personal branch.

### CODE REVIEW

**Comment by jxstanford** [comment]
based on conversation on another channel, let's add .gitmodules to .gitignore.  You will also want to add `prune desktop` to the `MANIFEST.in.oss` and `MANIFEST.in.enterprise` files so it doesn't get baked into the containers.

**Comment by lexjacobs** [comment]
Running `npm install` is now only required in the main repo.

**Comment by lexjacobs** [comment]
You will need to `rm -rf` node_modules in the /desktop directory, and run `npm install` from the top level of the main repo.

**Comment by jxstanford** [comment]
:+1: with caveat that I want to see how passing changes / PRs back and forth works in this scenario.  We removed .gitmodules to avoid confusion, but the `desktop` file with the submodule commit data is still here.  Not sure that will reduce confusion.

**Pull request merged**
