### PR TITLE
Tox install command missing from HACKING

### PR DESCRIPTION
**Pull request by stugots**

### CODE REVIEW

**Comment by lexjacobs** [comment]
:+1:

**Comment by jxstanford** [comment]
The container installs/upgrades tox upon creation, so not sure this is a required step in HACKING.  
```
docker/Dockerfiles/goldstone-app (master)]$ grep tox docker_entrypoint.sh                                      
    pip install --upgrade tox
```

**Comment by stugots** [comment]
Hmm... I added this because I deleted the app and db containers (docker rm goldstoneserver_gsappdev_1, etc...), and then re-started the VMs (bin/start...).  When I tried to run pep8 after everything finished, tox wasn't installed.

Does this mean there's something extra done when a container is created, over what is done when it's re-created?

**Comment by jxstanford** [comment]
ok, let's leave this tox statement in HACKING for now then.  It's probably an image versioning thing.  @heidecke and I are working through all that as we speak.

:+1:

**Pull request merged**
