### PR TITLE
Add swagger forms

### PR DESCRIPTION
**Pull request by stugots**
This fulfills the "some swagger docs missing input fields" ticket.

Pylint:
* master today: 9.56 / 10 / 9.7
* this pull: 9.57 / 10 / 9.7

To test, checkout this branch and refresh http://localhost:8000/docs/.  You don't have to restart your development server.

All the /nova/ API forms should now work.

### CODE REVIEW

**Comment by lexjacobs** [comment]
I saw your note about `/accounts/login/` . Sorry, I had forgotten that can't be included in swagger at this time.

There are some other swagger docs found that have a formatting issue that prevents the fields from appearing.

`/glance/`
image

(additional entries below have the same formatting issue as glance above)
`/keystone/*` 

`/logging/*`

`/api_perf/stats/`

**Comment by stugots** [comment]
Arg, I didn't check for others. My bad. I'll fix those too!

**Comment by stugots** [comment]
The other API endpoints' pages are now fixed.

(Except for /apiperf/stats/, which is fixed in the other outstanding pull request.)

**Comment by lexjacobs** [comment]
Formatting seems correct now for all calls.

Found at least a couple api calls for which the swagger options don't seem to match api implementation.

`/logging/events/summarize/`
name__prefix seems irrelevant for this call


`/logging/events/search/`
name__prefix only works for filtering 'name' key.
swagger forms don't allow for input of other strings before '__prefix'
missing 'page_size'

Are we going for 100% coverage between swagger and api calls as implemented in Goldstone?

**Comment by stugots** [comment]
When the API documentation doesn't match reality, we should fit it, unless that's not feasible.

I'll fix these.

**Comment by stugots** [comment]
> /logging/events/search/
> name__prefix only works for filtering 'name' key.

I don't understand the problem.  Can you explain?

**Comment by stugots** [comment]
/logging/events/[summarize, search]/ forms fixed, modulo my question about the name__prefix variable.

**Comment by lexjacobs** [comment]
Ah, meaning that "foo"__prefix=bar kicks an elasticSearch query against the foo key and returns results that begin with bar. So it's inflexible in that we can't specify different prefixes and in this case "name" isn't a key currently returned in the api payload.

**Comment by stugots** [comment]
Ah. Representing that in swagger-ui isn't possible, THBOMK. But I'll check the docs.

**Comment by lexjacobs** [comment]
All formatting issues cleared up. Per discussion with @stugots , will ticket swagger usability issues going forward.

**Comment by lexjacobs** [comment]
:+1:

**Pull request merged**
