### PR TITLE
Saved search event api

### LINKED ISSUE #282: Wire up events/api saved search dropdowns so they trigger a chart refresh.
Similar to the logBrowser viz which has a saved search dropdown, the api/events browsers have the same functionality via their own saved search dropdowns.

Hook them up so that a user selecting a saved search will trigger a chart refresh that reflects their saved searches.

### PR DESCRIPTION
**Pull request by lexjacobs**
Charts now 'do the right thing'.

to test, play around with the normal functionality + saved searches at:
http://localhost:8000/#reports/apibrowser
http://localhost:8000/#reports/eventbrowser

### server-side error found
NOTE: the 'service status' saved search on the /apibrowser page generates a 500 error.

image

query:
```
http://localhost:8000/core/saved_search/c7fa5f00-e851-4a71-9be0-7dbf8415426c/results/?@timestamp__range={%22gte%22:1455234742298,%22lte%22:1455235642298}&interval=45s&page_size=10&page=1
```

result:
```
{"message":"'int' object is not callable","detail":"There was an error processing this request. Please file a ticket with support."}
```

log output:
```
gsappdev_1 | [2016-02-12 00:10:12,452: INFO/MainProcess] Task goldstone.core.tasks.update_persistent_graph[d8d9b125-4f4c-4fda-86d3-93982e2917bb] succeeded in 8.819338447s: None
gsappdev_1 | [2016-02-12 00:10:12,461: INFO/MainProcess] Task goldstone.core.tasks.log_event_search[dd611ed9-372d-4244-b38b-b9b9f9199097] succeeded in 0.00828654599997s: True
gsappdev_1 | 2016-02-12T00:10:15+0000 ERROR    goldstone.core.utils 'int' object is not callable
gsappdev_1 | Traceback (most recent call last):
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
gsappdev_1 |     response = handler(request, *args, **kwargs)
gsappdev_1 |   File "/home/app/goldstone/core/views.py", line 486, in results
gsappdev_1 |     return HTTP_400_BAD_REQUEST("interval parameter not supported "
gsappdev_1 | TypeError: 'int' object is not callable
gsappdev_1 | [12/Feb/2016 00:10:15] "GET /core/saved_search/c7fa5f00-e851-4a71-9be0-7dbf8415426c/results/?@timestamp__range={%22gte%22:1455234921778,%22lte%22:1455235821778}&interval=45s&page_size=10&page=1&_all__regexp=.*dd.* HTTP/1.1" 500 132
```

closes #282

### CODE REVIEW

**Comment by jxstanford** [comment]
I added a couple of new searches under compliance (one for failed events, and one for slow API calls).  That highlighted one issue that I think we can correct on the client.  

When you POST a new saved search, please use the following values for doc_type field:

- log search:  `syslog`
- api search: `api_stats`
- event search: `don't include doc_type in body`

**Comment by jxstanford** [comment]
I've also added a 'hidden' field to the SavedSearches so you shouldn't see the `service status` search via the API anymore.

**Comment by jxstanford** [comment]
One final request:

Could you filter out the basic queries that you use for the page when a predefined search has not been selected (example `api call query`), and change the `None (reset...)` to just be `(reset)`

**Comment by lexjacobs** [comment]
`http://localhost:8000/core/saved_search/?name=service+status`

used by service status to return saved search uuid for service status viz.

returning []
`{"count":0,"next":null,"previous":null,"results":[]}`

image

**Comment by jxstanford** [comment]
unset the hidden flag for service status.  seems like you may want to maintain a list of searches that shouldn't show up in the list.

**Comment by lexjacobs** [comment]
@jxstanford 
re:

> Could you filter out the basic queries that you use for the page when a predefined search has not been selected (example api call query)

Is there a field to filter on, or just hard-code those to be ignored?
Also - can you use the backend 'hidden' attribute to not have them show up?

**Comment by lexjacobs** [comment]
@jxstanford  updates implemented

image


image

image

**Comment by jxstanford** [comment]
:+1:

**Comment by lexjacobs** [comment]
Reopening to merge branch.

**Comment by lexjacobs** [comment]
Closed again post-merge.

**Pull request merged**
